# Generated by Django 5.2.16 on 2026-07-11 16:00

import channel_manager.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, verbose_name='编号')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('text', models.TextField(blank=True, verbose_name='文字说明')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已上架'), ('UNPUBLISHING', '下架处理中'), ('UNPUBLISHED', '已下架'), ('ARCHIVED', '已归档')], db_index=True, default='DRAFT', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='定时上架')),
                ('cycle_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='循环间隔天数')),
                ('cycle_time', models.TimeField(blank=True, null=True, verbose_name='每天循环时间')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('anti_scan_enabled', models.BooleanField(default=False, verbose_name='防扫图处理')),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_no', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('sort_index', models.PositiveSmallIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('PHOTO', '图片'), ('VIDEO', '视频'), ('DOCUMENT', '文件')], max_length=16)),
                ('file', models.FileField(upload_to=channel_manager.models.content_upload_path)),
                ('processed_file', models.FileField(blank=True, upload_to=channel_manager.models.content_upload_path)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('telegram_file_ids_json', models.JSONField(blank=True, default=dict)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='channel_manager.content')),
            ],
            options={
                'ordering': ('group_no', 'sort_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_sequence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('WEB_USER', '网页用户'), ('TELEGRAM_USER', 'Telegram 用户'), ('SYSTEM', '系统')], max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(choices=[('WEB', '网页'), ('TELEGRAM', 'Telegram'), ('SCHEDULER', '定时器'), ('SYSTEM', '系统')], max_length=20)),
                ('action', models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '重发'), ('FORWARD', '转发'), ('REPLACE', '替换发布'), ('SYNC_TEXT', '文字同步')], max_length=20)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=80)),
                ('request_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('PENDING_CONFIRM', '待确认'), ('QUEUED', '排队中'), ('RUNNING', '执行中'), ('SUCCEEDED', '成功'), ('PARTIAL', '部分成功'), ('FAILED', '失败'), ('UNCERTAIN', '结果不确定'), ('CANCELLED', '已取消')], db_index=True, default='QUEUED', max_length=24)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('locked_by', models.CharField(blank=True, max_length=80)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('telegram_error_code', models.CharField(blank=True, max_length=80)),
                ('telegram_error_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(default='WEB_USER', max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='WEB', max_length=20)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('ACCEPTED', '已受理'), ('SUCCESS', '成功'), ('PARTIAL', '部分成功'), ('FAILED', '失败'), ('DENIED', '拒绝')], db_index=True, max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='channel_manager.operation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_bot_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('display_name', models.CharField(max_length=80, verbose_name='名称')),
                ('username', models.CharField(blank=True, max_length=80, verbose_name='Bot 用户名')),
                ('token_ciphertext', models.TextField()),
                ('webhook_secret_ciphertext', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('INVALID', 'Token 失效'), ('DISABLED', '已停用')], db_index=True, default='ACTIVE', max_length=16)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BotChannelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DEGRADED', '权限异常'), ('DISABLED', '已停用')], db_index=True, default='ACTIVE', max_length=16)),
                ('can_post_messages', models.BooleanField(default=False)),
                ('can_edit_messages', models.BooleanField(default=False)),
                ('can_delete_messages', models.BooleanField(default=False)),
                ('rights_json', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_bindings', to='channel_manager.telegrambot')),
            ],
            options={
                'ordering': ('channel', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram 频道 ID')),
                ('username', models.CharField(blank=True, max_length=80, verbose_name='频道用户名')),
                ('title', models.CharField(max_length=160, verbose_name='频道名称')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DEGRADED', '权限异常'), ('DISCONNECTED', '未连接')], db_index=True, default='DISCONNECTED', max_length=20)),
                ('route_policy', models.CharField(choices=[('PRIMARY_ONLY', '只使用主 Bot'), ('FAILOVER', '主 Bot 失败时切换'), ('EXPLICIT', '操作时指定 Bot')], default='PRIMARY_ONLY', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('PARTIAL', '部分成功'), ('ACTIVE', '活动'), ('DELETE_PENDING', '待删除'), ('DELETED', '已删除'), ('FAILED', '失败'), ('UNKNOWN', '未知')], db_index=True, default='PENDING', max_length=20)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('deletable_until', models.DateTimeField(blank=True, null=True)),
                ('bot_channel_binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='channel_manager.botchannelbinding')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='channel_manager.content')),
                ('replaces_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_deliveries', to='channel_manager.delivery')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='channel_manager.operation')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='channel_manager.telegramchannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel_manager.content')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channel_manager.telegramchannel')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='channels',
            field=models.ManyToManyField(related_name='contents', through='channel_manager.ContentChannel', to='channel_manager.telegramchannel'),
        ),
        migrations.AddField(
            model_name='botchannelbinding',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bot_bindings', to='channel_manager.telegramchannel'),
        ),
        migrations.CreateModel(
            name='TelegramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
                ('body_json', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('RECEIVED', '已接收'), ('PROCESSED', '已处理'), ('FAILED', '失败')], default='RECEIVED', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='channel_manager.telegrambot')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DISABLED', '已停用')], default='ACTIVE', max_length=16)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='channel_manager.telegrambot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChannelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_publish', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_resend', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='channel_manager.telegramchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_no', models.PositiveSmallIntegerField(default=1)),
                ('sort_index', models.PositiveSmallIntegerField(default=0)),
                ('telegram_message_id', models.BigIntegerField()),
                ('sent_by_bot_id', models.BigIntegerField(blank=True, null=True)),
                ('media_group_id', models.CharField(blank=True, max_length=100)),
                ('payload_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SENT', '已发送'), ('EDITED', '已编辑'), ('DELETED', '已删除'), ('UNKNOWN', '未知')], default='SENT', max_length=16)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channel_manager.delivery')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('delivery', 'telegram_message_id'), name='uniq_delivery_message')],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['state', 'available_at'], name='channel_man_state_c7e6d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('owner_user', 'idempotency_key'), name='uniq_owner_idempotency'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['owner_user', 'created_at'], name='channel_man_owner_u_74194f_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentchannel',
            constraint=models.UniqueConstraint(fields=('content', 'channel'), name='uniq_content_channel'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['owner_user', 'status', 'deleted_at'], name='channel_man_owner_u_9b51e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('owner_user', 'code'), name='uniq_owner_content_code'),
        ),
        migrations.AddConstraint(
            model_name='botchannelbinding',
            constraint=models.UniqueConstraint(fields=('bot', 'channel'), name='uniq_bot_channel'),
        ),
        migrations.AddConstraint(
            model_name='botchannelbinding',
            constraint=models.UniqueConstraint(fields=('channel', 'priority'), name='uniq_channel_priority'),
        ),
        migrations.AddConstraint(
            model_name='telegramupdate',
            constraint=models.UniqueConstraint(fields=('bot', 'update_id'), name='uniq_bot_update'),
        ),
        migrations.AddConstraint(
            model_name='telegramuserlink',
            constraint=models.UniqueConstraint(fields=('bot', 'telegram_user_id'), name='uniq_bot_telegram_user'),
        ),
        migrations.AddConstraint(
            model_name='userchannelaccess',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='uniq_user_channel'),
        ),
    ]
