# Generated by Django 5.2.16 on 2026-07-12 01:17

import channel_manager.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botchannelbinding',
            name='can_change_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='description',
            field=models.TextField(blank=True, verbose_name='频道简介'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=channel_manager.models.channel_photo_upload_path, verbose_name='频道头像'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已上架'), ('UNPUBLISHING', '下架处理中'), ('UNPUBLISHED', '已下架'), ('ARCHIVED', '已归档'), ('PARTIAL', '部分下架')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='action',
            field=models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '重发'), ('FORWARD', '转发'), ('REPLACE', '替换发布'), ('SYNC_TEXT', '文字同步'), ('UPDATE_CHANNEL', '修改频道资料'), ('EDIT_EXTERNAL', '编辑指定消息'), ('DELETE_EXTERNAL', '删除指定消息')], max_length=20),
        ),
        migrations.CreateModel(
            name='TelegramPendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '重发'), ('FORWARD', '转发'), ('REPLACE', '替换发布'), ('SYNC_TEXT', '文字同步'), ('UPDATE_CHANNEL', '修改频道资料'), ('EDIT_EXTERNAL', '编辑指定消息'), ('DELETE_EXTERNAL', '删除指定消息')], max_length=20)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', '等待确认'), ('CONFIRMED', '已确认'), ('CANCELLED', '已取消'), ('EXPIRED', '已过期')], db_index=True, default='PENDING', max_length=16)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='channel_manager.telegrambot')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_pending_actions', to='channel_manager.content')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_pending_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['bot', 'telegram_user_id', 'status'], name='channel_man_bot_id_74852f_idx')],
            },
        ),
    ]
