# Generated by Django 5.2.16 on 2026-07-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_manager', '0002_botchannelbinding_can_change_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='频道简介'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='频道名称'),
        ),
    ]
