# Generated by Django 5.2.16 on 2026-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_manager', '0003_alter_telegramchannel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text_variant',
            field=models.CharField(choices=[('SIMPLIFIED', '简体'), ('TRADITIONAL', '繁体')], default='SIMPLIFIED', max_length=16, verbose_name='发送文字'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='action',
            field=models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '重发'), ('FORWARD', '转发'), ('REPLACE', '编辑/自动更新重发'), ('SYNC_TEXT', '文字同步'), ('UPDATE_CHANNEL', '修改频道资料'), ('EDIT_EXTERNAL', '编辑指定消息'), ('DELETE_EXTERNAL', '删除指定消息')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrampendingaction',
            name='action',
            field=models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '重发'), ('FORWARD', '转发'), ('REPLACE', '编辑/自动更新重发'), ('SYNC_TEXT', '文字同步'), ('UPDATE_CHANNEL', '修改频道资料'), ('EDIT_EXTERNAL', '编辑指定消息'), ('DELETE_EXTERNAL', '删除指定消息')], max_length=20),
        ),
    ]
