# Generated by Django 5.2.16 on 2026-07-14 15:38

from django.db import migrations, models
from django.utils import timezone


def cancel_pending_manual_resends(apps, schema_editor):
    Operation = apps.get_model('channel_manager', 'Operation')
    TelegramPendingAction = apps.get_model('channel_manager', 'TelegramPendingAction')
    Operation.objects.filter(
        action='COPY',
        state__in=['PENDING_CONFIRM', 'QUEUED'],
    ).update(
        state='CANCELLED',
        finished_at=timezone.now(),
        telegram_error_code='FEATURE_REMOVED',
        telegram_error_text='手动重发功能已下线',
    )
    TelegramPendingAction.objects.filter(
        action='COPY',
        status='PENDING',
    ).update(status='CANCELLED')


class Migration(migrations.Migration):

    dependencies = [
        ('channel_manager', '0004_content_text_variant_alter_operation_action_and_more'),
    ]

    operations = [
        migrations.RunPython(cancel_pending_manual_resends, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userchannelaccess',
            name='can_resend',
        ),
        migrations.AlterField(
            model_name='operation',
            name='action',
            field=models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '历史重发（已停用）'), ('FORWARD', '转发'), ('REPLACE', '编辑/自动更新替换'), ('SYNC_TEXT', '文字同步'), ('UPDATE_CHANNEL', '修改频道资料'), ('EDIT_EXTERNAL', '编辑指定消息'), ('DELETE_EXTERNAL', '删除指定消息')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrampendingaction',
            name='action',
            field=models.CharField(choices=[('SEND', '发送'), ('EDIT', '编辑同步'), ('DELETE', '删除/下架'), ('COPY', '历史重发（已停用）'), ('FORWARD', '转发'), ('REPLACE', '编辑/自动更新替换'), ('SYNC_TEXT', '文字同步'), ('UPDATE_CHANNEL', '修改频道资料'), ('EDIT_EXTERNAL', '编辑指定消息'), ('DELETE_EXTERNAL', '删除指定消息')], max_length=20),
        ),
    ]
